PRODUCTS = [
    {
        "id": "leche-entera-fresca",
        "name": "Leche Entera Fresca",
        "detail": "1 litro",
        "category": "leche",
        "price": 6.50,
        "featured": True,
        "rating": 4.8,
        "image": "https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&w=900&q=85",
        "alt": "Botella de leche entera fresca",
    },
    {
        "id": "leche-semidescremada",
        "name": "Leche Semidescremada",
        "detail": "1 litro",
        "category": "leche",
        "price": 6.90,
        "featured": False,
        "rating": 4.5,
        "image": "https://images.unsplash.com/photo-1563636619-e9143da7973b?auto=format&fit=crop&w=900&q=85",
        "alt": "Botella de leche semidescremada",
    },
    {
        "id": "leche-descremada",
        "name": "Leche Descremada",
        "detail": "1 litro",
        "category": "leche",
        "price": 6.70,
        "featured": False,
        "rating": 4.4,
        "image": "https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&w=900&q=85",
        "alt": "Botella de leche descremada",
    },
    {
        "id": "yogurt-natural",
        "name": "Yogurt Natural",
        "detail": "200 gramos",
        "category": "yogurt",
        "price": 3.80,
        "featured": True,
        "rating": 4.9,
        "image": "https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=900&q=85",
        "alt": "Yogurt natural cremoso",
    },
    {
        "id": "yogurt-frutilla",
        "name": "Yogurt de Frutilla",
        "detail": "200 gramos",
        "category": "yogurt",
        "price": 4.20,
        "featured": True,
        "rating": 4.7,
        "image": "https://images.unsplash.com/photo-1571212515416-fef01fc43637?auto=format&fit=crop&w=900&q=85",
        "alt": "Yogurt de frutilla con fruta",
    },
    {
        "id": "yogurt-mermelada",
        "name": "Yogurt con Mermelada",
        "detail": "200 gramos",
        "category": "yogurt",
        "price": 4.80,
        "featured": False,
        "rating": 4.3,
        "image": "https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=900&q=85",
        "alt": "Yogurt con mermelada de frutas",
    },
    {
        "id": "queso-fresco",
        "name": "Queso Fresco",
        "detail": "500 gramos",
        "category": "queso",
        "price": 12.50,
        "featured": False,
        "rating": 4.6,
        "image": "https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?auto=format&fit=crop&w=900&q=85",
        "alt": "Queso fresco artesanal en bloque",
    },
    {
        "id": "queso-madurado",
        "name": "Queso Madurado",
        "detail": "500 gramos",
        "category": "queso",
        "price": 16.90,
        "featured": True,
        "rating": 4.9,
        "image": "https://images.unsplash.com/photo-1452195100486-9cc805987862?auto=format&fit=crop&w=900&q=85",
        "alt": "Queso madurado de corte",
    },
    {
        "id": "queso-ricotta",
        "name": "Queso Ricotta",
        "detail": "500 gramos",
        "category": "queso",
        "price": 11.90,
        "featured": False,
        "rating": 4.5,
        "image": "https://images.unsplash.com/photo-1628088062854-d1870b4553da?auto=format&fit=crop&w=900&q=85",
        "alt": "Queso ricotta cremoso",
    },
]